blank_issues_enabled: true
contact_links:
  - name: VSH / Freak Fortress Forum
    url: https://forums.alliedmods.net/forumdisplay.php?f=154
    about: Issue specific to your server, bosses, or subplugins.
  - name: Batfoxkid at Steam
    url: https://steamcommunity.com/profiles/76561198182419301
    about: If you want to discuss directly to the owner.
  - name: Batfoxkid at AlliedModders
    url: https://forums.alliedmods.net/private.php?do=newpm&u=289119
    about: If you want to discuss directly to the owner.
